## Section 2 Biomedical Data Science Workshop

In [2]:
import os
import numpy as np
import pandas as pd

In [ ]:
fp_inflammation = './data/inflammation-'

# row -> patient, col -> day
df_data1 = pd.read_csv(fp_inflammation + '01.csv', header=None)

In [ ]:
p1_ndarray = df_data1.to_numpy()
print(p1_ndarray)

[[0 0 1 ... 3 0 0]
 [0 1 2 ... 1 0 1]
 [0 1 1 ... 2 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 0 2 0]
 [0 0 1 ... 1 1 0]]


In [ ]:
print(type(p1_ndarray[0][0]))
print(type(p1_ndarray[0, 0]))

<class 'numpy.int64'>
<class 'numpy.int64'>


In [15]:
print(p1_ndarray[0:4, 0:10])

[[0 0 1 3 1 2 4 7 8 3]
 [0 1 2 1 2 1 3 2 2 6]
 [0 1 1 3 3 2 6 2 5 9]
 [0 0 2 0 4 2 2 1 6 7]]


In [16]:
small = p1_ndarray[:3, 36:]
print('small is:')
print(small)

small is:
[[2 3 0 0]
 [1 1 0 1]
 [2 2 1 1]]


In [18]:
print(np.mean(p1_ndarray))

maxval, minval, stdval = np.amax(p1_ndarray), np.amin(p1_ndarray), np.std(p1_ndarray)
print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

6.14875
maximum inflammation: 20
minimum inflammation: 0
standard deviation: 4.613833197118566


In [21]:
patient_1 = p1_ndarray[0, :] # 0 on the first axis (rows), everything on the second (columns)
print('maximum inflammation for patient 0:', np.amax(patient_1))

maximum inflammation for patient 0: 18


In [24]:
print('maximum inflammation for patients:\n', np.amax(p1_ndarray, axis=1))
print('maximum daily inflammation aross patients:\n', np.amax(p1_ndarray, axis=0))

maximum inflammation for patients:
 [18 18 19 17 17 18 17 20 17 18 18 18 17 16 17 18 19 19 17 19 19 16 17 15
 17 17 18 17 20 17 16 19 15 15 19 17 16 17 19 16 18 19 16 19 18 16 19 15
 16 18 14 20 17 15 17 16 17 19 18 18]
maximum daily inflammation aross patients:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 19 18 17
 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [27]:
print(np.mean(p1_ndarray, axis=0))
print(np.mean(p1_ndarray, axis=0).shape)
print(np.mean(p1_ndarray, axis=1))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]
(40,)
[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


In [33]:
element = 'oxygen'
print(element[1:-1])

xyge


In [41]:
patient3_week1 = p1_ndarray[3, :7]
print(patient3_week1)
p1_diffs = np.diff(p1_ndarray, axis=1)
p1_diffs_max = np.max(p1_diffs, axis=1)
print(p1_diffs_max)

[0 0 2 0 4 2 2]
[ 7 12 11 10 11 13 10  8 10 10  7  7 13  7 10 10  8 10  9 10 13  7 12  9
 12 11 10 10  7 10 11 10  8 11 12 10  9 10 13 10  7  7 10 13 12  8  8 10
 10  9  8 13 10  7 10  8 12 10  7 12]
